# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Remark"
license = "MIT"
licenselink = "https://github.com/anarcher/hugo-remark/blob/master/LICENSE"
description = ""
homepage = ""
tags = []
features = []
min_version = "0.41"

[author]
  name = "anarcher"
  homepage = "https://blog.anarcher.dev"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
